import { useEffect,useRef,useState } from 'react';
import { MotionConfig,useReducedMotion } from 'motion/react';
import Hero from './components/Hero';
import Inventory from './components/Inventory';
import Compression from './components/Compression';
import Workbench from './components/Workbench';
import { Chapter,Arrow,Mark,Reveal } from './components/Primitives';
import {essay,profile} from './content';
export default function App(){
 const prefersReduced=useReducedMotion();const [motionOff,setMotionOff]=useState(false);const reduced=Boolean(prefersReduced)||motionOff;
 const [dialog,setDialog]=useState<'read'|'contact'|null>(null);const dialogRef=useRef<HTMLDialogElement>(null);
 const [chapter,setChapter]=useState('01');
 useEffect(()=>{if(dialog)dialogRef.current?.showModal();else dialogRef.current?.close();},[dialog]);
 useEffect(()=>{document.documentElement.dataset.reduced=String(reduced);return()=>{delete document.documentElement.dataset.reduced;}},[reduced]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){const ids=['top','inventory','compression','work','about','contact'];setChapter(String(ids.indexOf(e.target.id)+1).padStart(2,'0'));}});},{rootMargin:'-20% 0px -45% 0px'});['top','inventory','compression','work','about','contact'].forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el);});return()=>observer.disconnect();},[]);
 return <MotionConfig reducedMotion={reduced?'always':'never'}><a href="#work" className="skip-link">Skip to work</a><header className="header"><a className="wordmark" href="#top">BEN<span className="accent">_</span></a><nav aria-label="Main navigation"><a href="#work">/ Work</a><button onClick={()=>setDialog('read')}>/ Writing</button><a href="#about">/ About</a><a href="#contact">/ Contact</a></nav></header><main><Hero reduced={reduced}/><Inventory reduced={reduced}/><Compression reduced={reduced}/><Workbench reduced={reduced} onRead={()=>setDialog('read')}/><section id="about" className="human section"><div className="human-image"><img src="/assets/desk.jpg" alt="Sunlight on a notebook and a small plant at a wooden desk" width="1415" height="1112" loading="lazy"/></div><Reveal reduced={reduced} className="human-copy"><Chapter number="05">The human layer</Chapter><h2>The point was<br/>never the<br/><em>machine.</em></h2><span className="short-rule"/><p>The point was getting enough control back to care for what matters.</p></Reveal></section><section id="contact" className="assembly section"><div className="assembly-top"><Chapter number="06">The final assembly</Chapter><Mark/></div><Reveal reduced={reduced}><h2>Building systems.<br/><em>Breaking cycles.</em></h2></Reveal><div className="final-links"><button onClick={()=>setDialog('read')}><Arrow/>Read</button><a href="#work"><Arrow/>Work</a><a href="#experiments"><Arrow/>Experiments</a>{profile.email?<a href={`mailto:${profile.email}`}><Arrow/>Contact</a>:<button onClick={()=>setDialog('contact')}><Arrow/>Contact</button>}</div><footer className="footer mono"><span><b>BEN</b> / Signal through noise</span><a href="#top">Back to top <Arrow/></a></footer></section></main><aside className="motion-dock" aria-label="Reading controls"><span>{chapter} / 06</span><button aria-pressed={reduced} onClick={()=>setMotionOff(v=>!v)} disabled={Boolean(prefersReduced)}>{reduced?'Motion reduced':'Reduce motion'}<span aria-hidden="true">{reduced?'○':'Ⅱ'}</span></button></aside><dialog ref={dialogRef} onCancel={()=>setDialog(null)} onClick={e=>{if(e.target===e.currentTarget)setDialog(null);}} aria-labelledby="dialog-title"><button className="dialog-close mono" onClick={()=>setDialog(null)}>Close <span aria-hidden="true">×</span></button>{dialog==='read'?<article className="essay"><span className="mono accent">FIELD NOTE / DRAFT</span><h2 id="dialog-title">{essay.title}</h2>{essay.paragraphs.map(p=><p key={p}>{p}</p>)}<span className="mono muted">A concept note for Signal Through Noise.</span></article>:<article className="essay"><span className="mono accent">CONTACT</span><h2 id="dialog-title">Start a conversation.</h2><p>A direct contact address will be here soon.</p><p>In the meantime, take a look around the workbench.</p><a href="#work" className="text-link" onClick={()=>setDialog(null)}>Explore the work <Arrow/></a></article>}</dialog></MotionConfig>
}
